name: Build FrogAIM APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Cordova
      run: |
        npm install -g cordova@11.0.0

    - name: Create Cordova project
      run: |
        cordova create android-app com.frogaim.cheat FrogAIM
        cp -r www/* android-app/www/
        cp config.xml android-app/

    - name: Add Android platform (compatible version)
      run: |
        cd android-app
        cordova platform add android@10.1.2

    - name: Build Android APK
      run: |
        cd android-app
        cordova build android

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: FrogAIM-APK
        path: android-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
