name: Build FrogAIM APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install -g @capacitor/cli
        npm install @capacitor/core @capacitor/android

    - name: Initialize Capacitor
      run: |
        npx cap init FrogAIM com.frogaim.cheat --web-dir www
        npx cap add android

    - name: Copy web files
      run: |
        cp -r www/* android/app/src/main/assets/public/
        cp config.xml android/app/src/main/assets/public/

    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: FrogAIM-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
